#GApps
$(call inherit-product, vendor/gms/gms_full.mk)

TARGET_BOOT_ANIMATION_RES := 1080
TARGET_GAPPS_ARCH := arm64
IS_PHONE := true
TARGET_INCLUDE_STOCK_ARCORE := true
TARGET_SUPPORTS_GOOGLE_RECORDER := true
DISABLE_DEFAULT_CAMERA := false
TARGET_INCLUDE_GAPPS := true
TARGET_GO_GAPPS := false

FLUID_BUILD_TYPE := UNOFFICIAL